config/routes.rb
Rails.application.routes.draw do
  resources :homeworks

  resources :assignments

  resources :students

  resources :classrooms

  root to: 'visitors#index'
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :classroom
  has_many :homeworks
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment.classroom, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:name, :classroom_id)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.haml
= simple_form_for(@assignment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.association :classroom

  .form-actions
    = f.button :submit

app/views/assignments/edit.html.haml
%h1 Editing assignment

= render 'form'

= link_to 'Show', @assignment
\|
= link_to 'Back', assignments_path

app/views/assignments/index.html.haml
%h1 Listing assignments

%table
  %thead
    %tr
      %th Name
      %th Classroom
      %th
      %th
      %th
      
  %tbody
    - @assignments.each do |assignment|
      %tr
        %td= assignment.name
        %td= assignment.classroom
        %td= link_to 'Show', assignment
        %td= link_to 'Edit', edit_assignment_path(assignment)
        %td= link_to 'Destroy', assignment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Assignment', new_assignment_path

app/views/assignments/new.html.haml
%h1 New assignment

= render 'form'

= link_to 'Back', assignments_path

app/views/assignments/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @assignment.name
%p
  %b Classroom:
  = @assignment.classroom

= link_to 'Edit', edit_assignment_path(@assignment)
\|
= link_to 'Back', assignments_path