config/routes.rb
Rails.application.routes.draw do
  resources :homeworks

  resources :assignments

  resources :students

  resources :classrooms

  root to: 'visitors#index'
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @classrooms = Classroom.all
    @students = Student.all
  end
end

app/views/visitors/_classrooms.html.haml
%h2 Classrooms:
%table#list-of-classrooms
  %thead
    %tr
      %th Name
      %th
      %th
      %th
  - @classrooms.each do |classroom|
    %tr
      %td= classroom.name
      %td= link_to 'Show', classroom
      %td= link_to 'Edit', edit_classroom_path(classroom)
      %td= link_to 'Destroy', classroom, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Classroom', new_classroom_path

app/views/visitors/_students.html.haml
%h2 Students:
%table#list-of-students
  %thead
    %tr
      %th Name
      %th
      %th
      %th
  - @students.each do |student|
    %tr
      %td= student.name
      %td= link_to 'Show', student
      %td= link_to 'Edit', edit_student_path(student)
      %td= link_to 'Destroy', student, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Student', new_student_path

app/views/visitors/index.html.haml
%h1 Welcome

%h5 From the home page you can:
%ul
  %li
    Create a new classroom by clicking the
    = link_to 'New Classroom', new_classroom_path
    link
  %li
    Create a new student by clicking the
    = link_to 'New Student', new_student_path
    link

%h5 From any given Classroom Show page:
%ul
  %li You can create assignments

%h5 From any given Student Show page:
%ul
  %li From any given Student Show page you can select which classes you want to enroll / unenroll the student from within the "Assign a student to classrooms" section.
  %li After a student is enrolled in a Classroom, you can have that student begin an assignment
  %li After a student has begun an assignment, they can input info in the "work" field and submit the assignment
  %li After a student has submitted an assignment it will show up in the "Submitted assignments" section

= render 'classrooms'

= render 'students'