config/routes.rb
Rails.application.routes.draw do
  resources :homeworks

  resources :assignments

  resources :students

  resources :classrooms

  root to: 'visitors#index'
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_and_belongs_to_many :classrooms
  has_many :homeworks
  has_many :assignments, through: :homeworks
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @classrooms = @student.classrooms
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to root_path, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :classroom_ids => [])
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_assign_student_to_classroom.html.haml
%h4 Assign a student to classrooms:
#assign-student-to-classroom
  = simple_form_for(@student) do |f|

    .form-inputs
      = f.association :classrooms, as: :check_boxes

    .form-actions
      = f.button :submit

app/views/students/_classroom_assignments.html.haml
%h4 Assignments:
%ul
  - if classroom.assignments.count < 1
    Visit the
    = link_to 'class show', classroom_path(classroom)
    page to add an assignment.
  - else
    - classroom.assignments.each do |assignment|
      %li{ id: "assignment-#{assignment.id}" }
        =assignment.name
        - if @student.assignments.include?(assignment)
          %p You're already working on this assignment
        - else
          = simple_form_for(Homework.new) do |f|
            = f.hidden_field :assignment_id, value: assignment.id
            = f.hidden_field :student_id, value: @student.id
            = f.button :submit, 'Begin working on assignment as homework', class: 'tiny'

app/views/students/_form.html.haml
= simple_form_for(@student) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit

app/views/students/_in_progress_homework.html.haml
%h4 In-progress assignments:
%div{ id: "homework-classroom-#{classroom.id}" }
  -classroom.homeworks.where(student_id: 1).where(submitted: false).each do |homework|
    %h5
      = homework.assignment.name
    = simple_form_for(homework) do |f|
      .form-inputs
        = f.input :work
        = f.hidden_field :submitted, value: true

      .form-actions
        = f.button :submit, 'Submit assignment'

    %hr

app/views/students/_submitted_homework.html.haml
%div{ id: "completed-classroom-#{classroom.id}" }
  %h4 Submitted assignments:
  -classroom.homeworks.where(student_id: 1).where(submitted: true).each do |homework|
    %h5
      = homework.assignment.name
    %p
      Work:
      = homework.work
    %hr

app/views/students/edit.html.haml
%h1 Editing student

= render 'form'

= link_to 'Show', @student
\|
= link_to 'Back', students_path

app/views/students/index.html.haml
%h1 Listing students

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
      
  %tbody
    - @students.each do |student|
      %tr
        %td= student.name
        %td= link_to 'Show', student
        %td= link_to 'Edit', edit_student_path(student)
        %td= link_to 'Destroy', student, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Student', new_student_path

app/views/students/new.html.haml
%h1 New student

= render 'form'

= link_to 'Back', root_path

app/views/students/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @student.name

%p
  %b Enrolled Classrooms:
  - @classrooms.each do |classroom|
    .classroom{ id: "classroom-#{classroom.id}" }
      %h3
        = classroom.name
      = render 'classroom_assignments', classroom: classroom
      = render 'in_progress_homework', classroom: classroom
      = render 'submitted_homework', classroom: classroom

= render 'assign_student_to_classroom'

= link_to 'Edit', edit_student_path(@student)
\|
= link_to 'Back', root_path