config/routes.rb
Rails.application.routes.draw do
  resources :homeworks

  resources :assignments

  resources :students

  resources :classrooms

  root to: 'visitors#index'
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :assignment
  belongs_to :student
  has_one :classroom, through: :assignment
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]

  # GET /homeworks
  # GET /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = Homework.new(homework_params)

    respond_to do |format|
      if @homework.save
        format.html { redirect_to @homework.student, notice: 'Homework was successfully created.' }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework.student, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_params
      params.require(:homework).permit(:work, :submitted, :assignment_id, :student_id)
    end
end

app/views/homeworks/_form.html.haml
= simple_form_for(@homework) do |f|
  = f.error_notification

  .form-inputs
    = f.input :work
    = f.input :submitted
    = f.association :assignment
    = f.association :student

  .form-actions
    = f.button :submit

app/views/homeworks/edit.html.haml
%h1 Editing homework

= render 'form'

= link_to 'Show', @homework
\|
= link_to 'Back', homeworks_path

app/views/homeworks/index.html.haml
%h1 Listing homeworks

%table
  %thead
    %tr
      %th Work
      %th Submitted
      %th Assignment
      %th Student
      %th
      %th
      %th
      
  %tbody
    - @homeworks.each do |homework|
      %tr
        %td= homework.work
        %td= homework.submitted
        %td= homework.assignment
        %td= homework.student
        %td= link_to 'Show', homework
        %td= link_to 'Edit', edit_homework_path(homework)
        %td= link_to 'Destroy', homework, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Homework', new_homework_path

app/views/homeworks/new.html.haml
%h1 New homework

= render 'form'

= link_to 'Back', homeworks_path

app/views/homeworks/show.html.haml
%p#notice= notice

%p
  %b Work:
  = @homework.work
%p
  %b Submitted:
  = @homework.submitted
%p
  %b Assignment:
  = @homework.assignment
%p
  %b Student:
  = @homework.student

= link_to 'Edit', edit_homework_path(@homework)
\|
= link_to 'Back', homeworks_path